daemon:
  tick_time: 60 # seconds
  log_file: tmp/ScoreEngineDaemon.log
  nofork: false

# Server Manager Configurtion
#server_manager:
#
# To configure an AWS Server Manager
#  add these configs to the settings.local.yml file
#  aws:
#    enable: true
#    region: *****
#    access_key_id: *****
#    secret_access_key: *****
#
# To use libvirt Server Manager
#  add these configs to the settings.local.yml file
#  libvirt:
#    enable: true
#    uri: *****